### ISSUE TITLE
Host IP Feature Request

### ISSUE THREAD

**Issue by cproudlock** [Tyrox92/GW2DPS---Group-DPS-Server#1]
I was wondering if it would be possible to allow domains/sub-domains along side of IP addresses as an entry method for Host IP?

For example, instead of giving out an IP Address, they would provide the raid with a Dynamic Domain Name ( http://www.noip.com/ ) that would automatically update when the Host's Dynamic IP address changed.

**Comment by Tyrox92** [comment]
This is working. Tested it out. Right now there is an limitation of characters set to 15.
So your DDNS cannot be longer than 15 at the moment. Will most likely be fixed in a future update.

Thank you for that question!

**Comment by cproudlock** [comment]
The input box for Host IP is restricted to 15 characters, which isn't enough space for the domain I'm trying to use. 

Thanks for the quick reply!

**Comment by Syphdias** [comment]
fixed, plus you can now use more ports
(this fix is client side)
