### ISSUE TITLE
QCoreApplication, not QApplication

### ISSUE THREAD

**Issue by Pluckerpluck** [Tyrox92/GW2DPS---Group-DPS-Server#2]
Can this be changed to use QCoreApplication (console) rather than arbitrarily opening a QApplication which does the exact same thing as a console.

It will work just the same but will open in native console. It also means I can run it on a server in a console (i.e. using SSH). It compiles and works on linux and it will just save people doing this change manually.

**Comment by Tyrox92** [comment]
Done. Will be in the next Version.
Thanks for the info!
